spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev

mybatis:
  type-aliases-package: com.lebrwcd.blog.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

comment.avatar: /images/avatar.png
message.avatar: /images/avatar.png




